import Header from '@/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/Navbar'
import Footer from '@/Footer'
import { Providers } from '../redux/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
